import produce from './produce';
import autokey from './autokey';

const assert = (x: boolean) => {
    if (!x) {
        throw(new Error(''));
    }
};

test('produce plain object', () => {
    const base = {
        a: 1,
        b: {
            c: 2,
            d: 3,
        }
    }
    const immutable = produce(base, (draft: any) => {
        draft.b.c = 6;
    })
    assert(base !== immutable);
    assert(base.b.c === 2);
    assert(immutable.b.c === 6);
})

test('autokey', () => {
    const base = {b: '1'};
    const autogenerated = autokey(base, (draft: any) => {
        draft.a.b.c.d.e = 'f';
    })
    console.log(JSON.stringify(autogenerated));
    assert(autogenerated.a.b.c.d.e === 'f');
})